/**
 * Appwrite client and database configuration.
 */

import { Client, Databases } from 'appwrite';
import {
  APPWRITE_ENDPOINT,
  APPWRITE_PROJECT,
  APPWRITE_DATABASE,
  APPWRITE_COLLECTION_CUSTOMERS,
  APPWRITE_COLLECTION_CYLINDER_TYPES,
  APPWRITE_COLLECTION_INVENTORY,
  APPWRITE_COLLECTION_MOVEMENTS,
  APPWRITE_COLLECTION_CUSTOMER_OWED,
  APPWRITE_COLLECTION_PRICES,
  APPWRITE_COLLECTION_FINANCE_TRANSACTIONS,
  APPWRITE_COLLECTION_CUSTOMER_BALANCE,
} from './env';

export const client = new Client()
  .setEndpoint(APPWRITE_ENDPOINT)
  .setProject(APPWRITE_PROJECT);

export const db = new Databases(client);

export const IDs = {
  database: APPWRITE_DATABASE,
  customers: APPWRITE_COLLECTION_CUSTOMERS,
  cylinder_types: APPWRITE_COLLECTION_CYLINDER_TYPES,
  inventory: APPWRITE_COLLECTION_INVENTORY,
  movements: APPWRITE_COLLECTION_MOVEMENTS,
  customer_owed: APPWRITE_COLLECTION_CUSTOMER_OWED,
  prices: APPWRITE_COLLECTION_PRICES,
  finance_transactions: APPWRITE_COLLECTION_FINANCE_TRANSACTIONS,
  customer_balance: APPWRITE_COLLECTION_CUSTOMER_BALANCE,
} as const;
